In [2]:
import numpy as np

rng = np.random.default_rng()

# Data types?


In [2]:
# a = rng.integers(low=0, high=1, endpoint=True, size=(1394300, 66))
# b = rng.integers(low=0, high=1, endpoint=True, size=(15300, 66))

# ushort_a = rng.integers(low=0, high=1, endpoint=True, size=(1394300, 66), dtype=np.ushort)
# ushort_b = rng.integers(low=0, high=1, endpoint=True, size=(15300, 66), dtype=np.ushort)

# uintc_a = rng.integers(low=0, high=1, endpoint=True, size=(1394300, 66), dtype=np.uintc)
# uintc_b = rng.integers(low=0, high=1, endpoint=True, size=(15300, 66), dtype=np.uintc)

# uint_a = rng.integers(low=0, high=1, endpoint=True, size=(1394300, 66), dtype=np.uint)
# uint_b = rng.integers(low=0, high=1, endpoint=True, size=(15300, 66), dtype=np.uint)

# bool_a = rng.integers(low=0, high=1, endpoint=True, size=(13943, 66), dtype=np.bool_)
# bool_b = rng.integers(low=0, high=1, endpoint=True, size=(15300, 66), dtype=np.bool_)

In [3]:
# %timeit np.dot(a, b.T)
# %timeit np.dot(ushort_a, ushort_b.T)
# %timeit np.dot(uintc_a, uintc_b.T)
# %timeit np.dot(uint_a, uint_b.T)
# %timeit np.dot(bool_a, bool_b.T)

# Implementation of matrix multiplication?

In [4]:
# %timeit np.matmul(a, b.T)
# %timeit np.matmul(ushort_a, ushort_b.T)
# %timeit np.matmul(uintc_a, uintc_b.T)
# %timeit np.matmul(uint_a, uint_b.T)
# %timeit np.matmul(bool_a, bool_b.T)

In [5]:
# np.array_equal(np.dot(bool_a, bool_b.T), np.matmul(bool_a, bool_b.T))

In [6]:
a = np.array([[1,1,0]], dtype=bool)
b = np.array([[1,0,1]], dtype=bool)
print(a)
print(b)
a + b

[[ True  True False]]
[[ True False  True]]


array([[ True,  True,  True]])

In [19]:
a = np.array([[1,1,0],[0,1,1]], dtype=bool).T
b = np.array([[1,1,0],[0,1,1]], dtype=bool)

np.matmul(a, b, dtype=int)

array([[1, 1, 0],
       [1, 2, 1],
       [0, 1, 1]])

In [26]:
a = np.arange(10, dtype=int)
print(a)
b = np.hstack(np.split(a, (3, 6))[::2])
print(b)
b[1] = 100
print(a)
%timeit tuple(b)
%timeit b.tobytes()

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
5.11 µs ± 245 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
409 ns ± 10.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [28]:
np.union1d(a, b)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9, 100])

In [31]:
da = {'a': 1, 'b': 2}
db = {'a': 100, 'b': 100, 'c': 200}
dc = {**da, **db}
dc

{'a': 100, 'b': 100, 'c': 200}